### ISSUE TITLE
narrative synthesis vignette

### ISSUE THREAD

**Issue by softloud** [softloud/sysrevdata#28]
# objective

Vignette ready to ship with manuscript. 

# notes

The bufferstrips csv is in the ideal format. 

:thinking: @DrMattG I wonder how best to structure a vignette for this. I think maybe I'll try to construct a minimalist example on toy data. 

# tasks

- [x] create vignette document 
- [x] discuss bufferstrips as ideal format
- [x] create minimalist toy example of joining a few wide toy datasets
- [x] create minimalist toy example of joining a few long toy datasets
- [x] rebuild site & push
- [x] ping to @DrMattG for checking 
- [x] ping to @nealhaddaway for checking

**Comment by DrMattG** [comment]
@softloud I think using toy data is fine here. As far as I understand it - this will be more "free form" than the other two vignettes. We could show some of the types of viz that could be used.... not sure about that.. Push up your changes and I will have a look.
