### ISSUE TITLE
systematic map and complex visualisation vignette

### ISSUE THREAD

**Issue by softloud** [softloud/sysrevdata#29]
# objective

Structuring data for systematic map vignette ready to ship with manuscript.

# notes

Be able to summarise data by key variables: number of studies per year, country, variables per study. 

:thinking: Currently thinking I should combine this vignette with the complex visualisation vignette because the under the hood it will likely be the same

# tasks

- [x] create vignette
- [x] condensed to long toy example
- [x] wide to long toy example
- [x] show how data can be used for summary outputs
- [x] create a systematic map from toy data
- [x] create a complex visualisation
- [x] build site & push
