### ISSUE TITLE
disaggregation

### ISSUE THREAD

**Issue by softloud** [softloud/sysrevdata#30]
# objective 

Vignette about extracting data into machine readable format.

# notes

Examples of nicely structured data

- Nicola Randall for example of wide
- Bernes for hybrid

# tasks

- [ ] create document
- [ ] condensed to long toy example
- [ ] wide/spare to long toy example
- [ ] discussion of examples from papers
- [ ] build site & push
